---
# Kubernetes
kubernetes_version: "1.34"
kubernetes_package_version: "1.34.11"

# Kubernetes networking
pod_network_cidr: "10.244.0.0/16"

# Cilium
cilium_cli_version: "latest"
cilium_hubble_enabled: true
cilium_hubble_relay_enabled: true