---
- name: Check if node is already part of a Kubernetes cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config

- name: Join worker node to Kubernetes cluster
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['control_plane'][0]]['kubeadm_join_command'].stdout }}"
  when: not kubelet_config.stat.exists